title = "System Information Config"

[display]
format = "CONSOLE"  # Options: "CONSOLE", "FILE"
file_path = "system_info_output.txt"

[[fields]]
name = "os"
displayName = "Operating System"

[[fields]]
name = "cpu_usage"
displayName = "CPU Usage"

[[fields]]
name = "memory_usage"
displayName = "Memory Usage"
